In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [4]:
task_1=np.arange(0,9,1)
print(task_1)

[0 1 2 3 4 5 6 7 8]


In [7]:
task_2=np.full((3,3), True, dtype=bool)
print(task_2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
task_3=np.arange(1,10,1)
print(task_3)
print(task_3[0:10:2])
for i in range(0,len(task_3),2):
    task_3[i]=-1   
print(task_3)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[-1  2 -1  4 -1  6 -1  8 -1]


In [23]:
task_5=np.array([1,2,3,4,5,6,7,8])
print(task_5)
new_task_5=task_5.reshape(2,4)
print(new_task_5)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [33]:
a=np.array([[1],[2],[3]])
b=np.array([[1],[2],[3]])
print(a)
print(b)
c=np.vstack((a,b))
print(c)
task_6=np.sum(c)
print("La suma de todos los valores del vector es",task_6)


[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]
La suma de todos los valores del vector 12


In [42]:
array_1=np.ones(3)
print(array_1)
array_2=array_1*4
array_3=array_1*3
array_4=np.arange(1,4)
print(array_2,array_3,array_4)
task_7=np.concatenate((array_1,array_2,array_3,array_4),axis=0)
print(task_7)


[1. 1. 1.]
[2. 2. 2.] [3. 3. 3.] [1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3.]


In [45]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
for i in range (len(a)):
    for j in range (len(b)):
        if a[i]==b[j]:
            b[j]=0
print(a)
print(b)

[1 2 3 4 5]
[0 0 6 7 8 9]


In [52]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
for i in range(len(a)):
    if 3<=a[i]<=7:
        a[i]=a[i]
    else:
        a[i]=0
print(a)
for i in range(len(b)):
    if 3<=b[i]<=7:
        b[i]=b[i]
    else:
        b[i]=0
print(b)

task_9=np.concatenate((a,b),axis=0)
print(task_9)

sum=0
for i in range(len(task_9)):
    sum=sum+task_9[i]
print(sum)

sum_2=np.sum(task_9)
print(sum_2)

[0 0 3 4 5]
[4 5 6 7 0 0]
[0 0 3 4 5 4 5 6 7 0 0]
34
34
